// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Sale;

[Table("AccountKey")]
[Index("AccountKey1", Name = "IDX_UNIQUE_AccountKey", IsUnique = true)]
public partial class AccountKey
{
    [Key]
    public long AccountId { get; set; }

    /// <summary>
    /// 통합인보이스 등에서 사용되는 AccountKey. (AccountId를 기반으로 generated 한 값)
    /// </summary>
    [Column("AccountKey")]
    [StringLength(7)]
    [Unicode(false)]
    public string? AccountKey1 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RegDate { get; set; }
}