// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Sale;

public partial class SaleContext : DbContext
{
    public SaleContext(DbContextOptions<SaleContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountKey> AccountKeys { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountKey>(entity =>
        {
            entity.Property(e => e.AccountId).ValueGeneratedNever();
            entity.Property(e => e.AccountKey1)
                .HasComputedColumnSql("(CONVERT([varchar](7),concat(reverse(right('0000'+CONVERT([varchar](4),CONVERT([varbinary](2),[AccountId]),(2)),(4))),reverse(right('000000'+isnull(CONVERT([varchar](100),checksum([AccountId],[AccountId])),'0'),(3))))))", true)
                .HasComment("통합인보이스 등에서 사용되는 AccountKey. (AccountId를 기반으로 generated 한 값)");
            entity.Property(e => e.RegDate).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}