// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Iam;

[Table("ServiceHierarchy_Config")]
public partial class ServiceHierarchyConfig
{
    [Key]
    public long ConfigId { get; set; }

    public long Sno { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string ConfigCode { get; set; } = null!;

    public double ConfigValue { get; set; }

    [ForeignKey("Sno")]
    [InverseProperty("ServiceHierarchyConfigs")]
    public virtual ServiceHierarchy SnoNavigation { get; set; } = null!;
}