// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Iam;

[Table("Tenant")]
[Index("RealmName", "OwnerId", Name = "IDX_Tenant_RealmName_OwnerId", IsUnique = true)]
[Index("TenantId", Name = "IDX_Tenant_TenantId", IsUnique = true)]
public partial class Tenant
{
    [StringLength(50)]
    [Unicode(false)]
    public string TenantId { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string RealmName { get; set; } = null!;

    public long OwnerId { get; set; }

    [Column("TUId")]
    public Guid Tuid { get; set; }

    [Key]
    [Column("SNo")]
    public long Sno { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [StringLength(1000)]
    public string? Remark { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SavedAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? SaverId { get; set; }

    [InverseProperty("Tenant")]
    public virtual ICollection<ServiceHierarchy> ServiceHierarchies { get; set; } = new List<ServiceHierarchy>();
}