// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

[Table("BillingRole")]
public partial class BillingRole
{
    [Key]
    [Column("SNo")]
    public long Sno { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RoleId { get; set; } = null!;

    [StringLength(200)]
    public string Alias { get; set; } = null!;
}