// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

public partial class BillContext : DbContext
{
    public BillContext(DbContextOptions<BillContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bill> Bills { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bill>(entity =>
        {
            entity.HasKey(e => e.BillId).HasName("PK_Bill_BillId");

            entity.Property(e => e.SavedAt).HasDefaultValueSql("(dateadd(hour,(-9),getdate()))");
            entity.Property(e => e.TotalAmount).HasComputedColumnSql("(CONVERT([money],[Amount]+[Tax]))", true);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}