// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

[Table("Bill")]
[Index("BillMonth", Name = "idx_Bill_BillMonth")]
public partial class Bill
{
    [Key]
    public long BillId { get; set; }

    public DateOnly BillDate { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string? BillMonth { get; set; }

    public long SellerAccountId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? SellerManagerId { get; set; }

    public long BuyerAccountId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? BuyerManagerId { get; set; }

    [StringLength(7)]
    [Unicode(false)]
    public string StatusCode { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? ConsumptionStartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ConsumptionEndDate { get; set; }

    [StringLength(7)]
    [Unicode(false)]
    public string CurrencyCode { get; set; } = null!;

    [Column(TypeName = "money")]
    public decimal ConsumptionAmount { get; set; }

    [Column(TypeName = "money")]
    public decimal DiscountAmount { get; set; }

    [Column(TypeName = "money")]
    public decimal ExtraAmount { get; set; }

    [Column(TypeName = "money")]
    public decimal Amount { get; set; }

    [Column(TypeName = "money")]
    public decimal Tax { get; set; }

    [Column(TypeName = "money")]
    public decimal? TotalAmount { get; set; }

    [StringLength(1000)]
    public string? Remark { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SavedAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? SaverId { get; set; }
}