// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

[Table("BillItem")]
[Index("BillId", Name = "idx_BillItem_BillId")]
public partial class BillItem
{
    /// <summary>
    /// 청구번호
    /// </summary>
    public long BillId { get; set; }

    /// <summary>
    /// 청구품목번호
    /// </summary>
    [Key]
    public long BillItemId { get; set; }

    /// <summary>
    /// 상품번호 -&gt; e.g., NCP, AWS, 매니지드서비스, 프로모션할인
    /// </summary>
    public long? ProductId { get; set; }

    /// <summary>
    /// 청구통화코드 #CUR (E.g., KRW, JPY)
    /// </summary>
    [StringLength(7)]
    [Unicode(false)]
    public string CurrencyCode { get; set; } = null!;

    /// <summary>
    /// 공급가액
    /// </summary>
    [Column(TypeName = "money")]
    public decimal Amount { get; set; }

    /// <summary>
    /// 적요
    /// </summary>
    [StringLength(500)]
    public string? Description { get; set; }

    /// <summary>
    /// Default: current_timestamp
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime SavedAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? SaverId { get; set; }

    [ForeignKey("BillId")]
    [InverseProperty("BillItems")]
    public virtual Bill Bill { get; set; } = null!;

    [ForeignKey("ProductId")]
    [InverseProperty("BillItems")]
    public virtual Product? Product { get; set; }
}