// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

/// <summary>
/// 청구서 벤더 디테일 테이블
/// </summary>
[Table("BillDetail")]
[Index("BillItemId", Name = "idx_BillDetail_BillItemId")]
[Index("BillItemId", "VendorCode", "KeyId", Name = "idx_unique_BillDetail_BillItemId_VendorCode_LineId", IsUnique = true)]
public partial class BillDetail
{
    /// <summary>
    /// 청구품목번호
    /// </summary>
    public long BillItemId { get; set; }

    /// <summary>
    /// 청구상세번호
    /// </summary>
    [Key]
    public long BillDetailId { get; set; }

    /// <summary>
    /// #VEN 벤더코드
    /// </summary>
    [StringLength(7)]
    [Unicode(false)]
    public string VendorCode { get; set; } = null!;

    /// <summary>
    /// demandMonth-zone-account-memberNo
    /// </summary>
    [StringLength(500)]
    [Unicode(false)]
    public string KeyId { get; set; } = null!;

    [ForeignKey("BillItemId")]
    [InverseProperty("BillDetails")]
    public virtual BillItem BillItem { get; set; } = null!;
}