// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

[Table("NCP_Detail")]
[Index("DemandMonth", "MemberNo", Name = "idx_NCP_Detail_demandMonth_memberNo")]
public partial class NcpDetail
{
    [Key]
    public long DetailLineId { get; set; }

    [Column("batchDate")]
    public DateOnly? BatchDate { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string? KeyId { get; set; }

    [Column("demandMonth")]
    [StringLength(6)]
    [Unicode(false)]
    public string DemandMonth { get; set; } = null!;

    [Column("zone")]
    [StringLength(30)]
    [Unicode(false)]
    public string Zone { get; set; } = null!;

    [Column("account")]
    [StringLength(30)]
    [Unicode(false)]
    public string Account { get; set; } = null!;

    [Column("memberNo")]
    [StringLength(20)]
    [Unicode(false)]
    public string MemberNo { get; set; } = null!;

    [Column("memberName")]
    [StringLength(300)]
    public string? MemberName { get; set; }

    [Column("writeDate", TypeName = "datetime")]
    public DateTime WriteDate { get; set; }

    [Column("regionCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string? RegionCode { get; set; }

    [Column("demandType_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? DemandTypeCode { get; set; }

    [Column("demandType_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? DemandTypeCodeName { get; set; }

    [Column("demandTypeDetail_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? DemandTypeDetailCode { get; set; }

    [Column("demandTypeDetail_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? DemandTypeDetailCodeName { get; set; }

    [Column("contract_memberNo")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractMemberNo { get; set; }

    [Column("contract_contractNo")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractContractNo { get; set; }

    [Column("contract_conjunctionContractNo")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractConjunctionContractNo { get; set; }

    [Column("contract_contractType_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractContractTypeCode { get; set; }

    [Column("contract_contractType_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractContractTypeCodeName { get; set; }

    [Column("contract_contractStatus_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractContractStatusCode { get; set; }

    [Column("contract_contractStatus_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractContractStatusCodeName { get; set; }

    [Column("contract_contractStartDate", TypeName = "datetime")]
    public DateTime? ContractContractStartDate { get; set; }

    [Column("contract_contractEndDate", TypeName = "datetime")]
    public DateTime? ContractContractEndDate { get; set; }

    [Column("contract_instanceName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractInstanceName { get; set; }

    [Column("contract_regionCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractRegionCode { get; set; }

    [Column("contract_platformType_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractPlatformTypeCode { get; set; }

    [Column("contract_platformType_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractPlatformTypeCodeName { get; set; }

    [Column("contractProductList_contractProductSequence")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListContractProductSequence { get; set; }

    [Column("contractProductList_beforeContractProductSequence")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListBeforeContractProductSequence { get; set; }

    [Column("contractProductList_productCode")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractProductListProductCode { get; set; }

    [Column("contractProductList_priceNo")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListPriceNo { get; set; }

    [Column("contractProductList_promiseNo")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListPromiseNo { get; set; }

    [Column("contractProductList_instanceNo")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListInstanceNo { get; set; }

    [Column("contractProductList_productItemKind_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListProductItemKindCode { get; set; }

    [Column("contractProductList_productItemKind_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractProductListProductItemKindCodeName { get; set; }

    [Column("contractProductList_productRatingType_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListProductRatingTypeCode { get; set; }

    [Column("contractProductList_productRatingType_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractProductListProductRatingTypeCodeName { get; set; }

    [Column("contractProductList_serviceStatus_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListServiceStatusCode { get; set; }

    [Column("contractProductList_serviceStatus_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractProductListServiceStatusCodeName { get; set; }

    [Column("contractProductList_serviceStartDate", TypeName = "datetime")]
    public DateTime? ContractProductListServiceStartDate { get; set; }

    [Column("contractProductList_serviceEndDate", TypeName = "datetime")]
    public DateTime? ContractProductListServiceEndDate { get; set; }

    [Column("contractProductList_productSize")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListProductSize { get; set; }

    [Column("contractProductList_productCount")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ContractProductListProductCount { get; set; }

    [Column("contractProductList_usageList")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ContractProductListUsageList { get; set; }

    [Column("unitUsageQuantity")]
    public double? UnitUsageQuantity { get; set; }

    [Column("packageUnitUsageQuantity")]
    public double? PackageUnitUsageQuantity { get; set; }

    [Column("totalUnitUsageQuantity")]
    public double? TotalUnitUsageQuantity { get; set; }

    [Column("usageUnit_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? UsageUnitCode { get; set; }

    [Column("usageUnit_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? UsageUnitCodeName { get; set; }

    [Column("productPrice")]
    public double? ProductPrice { get; set; }

    [Column("useAmount", TypeName = "money")]
    public decimal? UseAmount { get; set; }

    [Column("promotionDiscountAmount", TypeName = "money")]
    public decimal? PromotionDiscountAmount { get; set; }

    [Column("etcDiscountAmount", TypeName = "money")]
    public decimal? EtcDiscountAmount { get; set; }

    [Column("promiseDiscountAmount", TypeName = "money")]
    public decimal? PromiseDiscountAmount { get; set; }

    [Column("demandAmount", TypeName = "money")]
    public decimal? DemandAmount { get; set; }

    [Column("memberPriceDiscountAmount", TypeName = "money")]
    public decimal? MemberPriceDiscountAmount { get; set; }

    [Column("memberPromiseDiscountAddAmount", TypeName = "money")]
    public decimal? MemberPromiseDiscountAddAmount { get; set; }

    [Column("payCurrency_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string? PayCurrencyCode { get; set; }

    [Column("payCurrency_codeName")]
    [StringLength(300)]
    [Unicode(false)]
    public string? PayCurrencyCodeName { get; set; }

    [Column("sectionPriceList")]
    [StringLength(50)]
    [Unicode(false)]
    public string? SectionPriceList { get; set; }

    [Column("thisMonthAppliedExchangeRate")]
    public double? ThisMonthAppliedExchangeRate { get; set; }

    [Column("requestId")]
    [StringLength(50)]
    [Unicode(false)]
    public string? RequestId { get; set; }

    [Column("returnCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string? ReturnCode { get; set; }

    [Column("returnMessage")]
    [StringLength(300)]
    [Unicode(false)]
    public string? ReturnMessage { get; set; }
}