// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

[Table("NCP_MarginExceptProduct")]
public partial class NcpMarginExceptProduct
{
    [Key]
    public long Sno { get; set; }

    public bool IsActive { get; set; }

    [StringLength(100)]
    public string Operator { get; set; } = null!;

    [StringLength(200)]
    public string ProductName { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime SavedAt { get; set; }
}