// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

[Table("NCP_Member")]
public partial class NcpMember
{
    [Key]
    [Column("memberNo")]
    [StringLength(20)]
    [Unicode(false)]
    public string MemberNo { get; set; } = null!;

    [Column("memberName")]
    [StringLength(300)]
    public string? MemberName { get; set; }
}