// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

[Table("NCP_Master")]
[Index("DemandMonth", "MemberNo", Name = "idx_NCP_Master_demandMonth_memberNo")]
public partial class NcpMaster
{
    [Key]
    public long LineId { get; set; }

    [Column("batchDate")]
    public DateOnly? BatchDate { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string? KeyId { get; set; }

    [Column("demandMonth")]
    [StringLength(6)]
    [Unicode(false)]
    public string DemandMonth { get; set; } = null!;

    [Column("zone")]
    [StringLength(30)]
    [Unicode(false)]
    public string Zone { get; set; } = null!;

    [Column("account")]
    [StringLength(30)]
    [Unicode(false)]
    public string Account { get; set; } = null!;

    [Column("memberNo")]
    [StringLength(20)]
    [Unicode(false)]
    public string MemberNo { get; set; } = null!;

    [Column("memberName")]
    [StringLength(300)]
    public string? MemberName { get; set; }

    [Column("writeDate", TypeName = "datetime")]
    public DateTime WriteDate { get; set; }

    [Column("useAmount", TypeName = "money")]
    public decimal? UseAmount { get; set; }

    [Column("promiseDiscountAmount", TypeName = "money")]
    public decimal? PromiseDiscountAmount { get; set; }

    [Column("memberPriceDiscountAmount", TypeName = "money")]
    public decimal? MemberPriceDiscountAmount { get; set; }

    [Column("memberPromiseDiscountAddAmount", TypeName = "money")]
    public decimal? MemberPromiseDiscountAddAmount { get; set; }

    [Column("etcDiscountAmount", TypeName = "money")]
    public decimal? EtcDiscountAmount { get; set; }

    [Column("promotionDiscountAmount", TypeName = "money")]
    public decimal? PromotionDiscountAmount { get; set; }

    [Column("demandAmount", TypeName = "money")]
    public decimal? DemandAmount { get; set; }

    [Column("discountTargetAmount", TypeName = "money")]
    public decimal? DiscountTargetAmount { get; set; }

    [Column("discountAppliedAmount", TypeName = "money")]
    public decimal? DiscountAppliedAmount { get; set; }

    [Column("discountName")]
    [StringLength(200)]
    [Unicode(false)]
    public string? DiscountName { get; set; }

    [Column("productDiscountAmount", TypeName = "money")]
    public decimal? ProductDiscountAmount { get; set; }

    [Column("creditDiscountAmount", TypeName = "money")]
    public decimal? CreditDiscountAmount { get; set; }

    [Column("customerDiscountAmount", TypeName = "money")]
    public decimal? CustomerDiscountAmount { get; set; }

    [Column("rounddownDiscountAmount", TypeName = "money")]
    public decimal? RounddownDiscountAmount { get; set; }

    [Column("currencyDiscountAmount", TypeName = "money")]
    public decimal? CurrencyDiscountAmount { get; set; }

    [Column("coinUseAmount", TypeName = "money")]
    public decimal? CoinUseAmount { get; set; }

    [Column("defaultAmount", TypeName = "money")]
    public decimal? DefaultAmount { get; set; }

    [Column("totalDemandAmount", TypeName = "money")]
    public decimal? TotalDemandAmount { get; set; }

    [Column("totalMarginExceptProductUseAmount", TypeName = "money")]
    public decimal? TotalMarginExceptProductUseAmount { get; set; }

    [Column("totalExceptProductMarginAmount", TypeName = "money")]
    public decimal? TotalExceptProductMarginAmount { get; set; }

    [Column("marginRatio", TypeName = "money")]
    public decimal? MarginRatio { get; set; }

    [Column("marginAmount", TypeName = "money")]
    public decimal? MarginAmount { get; set; }

    [Column("marginDiscountAmount", TypeName = "money")]
    public decimal? MarginDiscountAmount { get; set; }

    [Column("partnerTotalDemandAmount", TypeName = "money")]
    public decimal? PartnerTotalDemandAmount { get; set; }

    [Column("currencyPartnerTotalDemandAmount", TypeName = "money")]
    public decimal? CurrencyPartnerTotalDemandAmount { get; set; }

    [Column("currencyPartnerTotalDemandVatAmount", TypeName = "money")]
    public decimal? CurrencyPartnerTotalDemandVatAmount { get; set; }

    [Column("currencyPartnerTotalDemandAmountIncludingVat", TypeName = "money")]
    public decimal? CurrencyPartnerTotalDemandAmountIncludingVat { get; set; }

    [Column("partnerPayCurrency_code")]
    [StringLength(10)]
    [Unicode(false)]
    public string? PartnerPayCurrencyCode { get; set; }

    [Column("thisMonthPartnerAppliedExchangeRate")]
    public double? ThisMonthPartnerAppliedExchangeRate { get; set; }

    [Column("payCurrency_code")]
    [StringLength(10)]
    [Unicode(false)]
    public string? PayCurrencyCode { get; set; }
}