// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models.Bill;

/// <summary>
/// 제공 상품 정보
/// </summary>
[Table("Product")]
public partial class Product
{
    /// <summary>
    /// 상품번호
    /// </summary>
    [Key]
    public long ProductId { get; set; }

    /// <summary>
    /// 상품명
    /// </summary>
    [StringLength(200)]
    public string ProductName { get; set; } = null!;

    /// <summary>
    /// Default:1 활성여부
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 비고
    /// </summary>
    [StringLength(1000)]
    public string? Remark { get; set; }

    [StringLength(7)]
    [Unicode(false)]
    public string ProductCode { get; set; } = null!;

    /// <summary>
    /// Default: current_timestamp
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime SavedAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? SaverId { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<BillItem> BillItems { get; set; } = new List<BillItem>();
}