// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Billing.Data.Models;

public partial class Org
{
    public long OrgSno { get; set; }

    public string TenantId { get; set; } = null!;

    public long ParentAccId { get; set; }

    /// <summary>
    /// 자식 account id
    /// </summary>
    public long AccountId { get; set; }

    public bool IsActive { get; set; }

    /// <summary>
    /// 계약 시작 일(미확정)
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// 계약 만료 일(미확정)
    /// </summary>
    public DateTime EndDate { get; set; }

    public DateTime SavedAt { get; set; }

    public string? SaverId { get; set; }
}