// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Billing.Data.Models;

[Table("ServiceHierarchy")]
public partial class ServiceHierarchy
{
    [Key]
    public long Sno { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TenantId { get; set; } = null!;

    public long ParentAccId { get; set; }

    public long AccountId { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SavedAt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? SaverId { get; set; }

    [ForeignKey("TenantId")]
    [InverseProperty("ServiceHierarchies")]
    public virtual Tenant Tenant { get; set; } = null!;
}