// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Billing.Data.Models;

public partial class Tenant
{
    public string? TenantId { get; set; }

    public string RealmName { get; set; } = null!;

    public long OwnerId { get; set; }

    public Guid Tuid { get; set; }

    public long Sno { get; set; }

    public bool IsActive { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string? Remark { get; set; }

    public DateTime SavedAt { get; set; }

    public string? SaverId { get; set; }
}